### ISSUE TITLE
Can't scroll enough if dialog content is taller than page content

### ISSUE THREAD

**Issue by peterchappell** [tornqvist/dialog#3]
Thanks so much for making this plugin. It's hard to find a dialog/modal that works this well on both desktop and mobile.

When playing around to see if I can use the plugin on my project I was testing what would happen if I have _lots_ of content in the dialog but not much on the page (i.e. the page doesn't scroll but the dialog needs to).

Unfortunately the dialog gets truncated in this case. 

It would be nice if the plugin checks the height of the dialog content against the height of the body and compensates if necessary.

**Comment by tornqvist** [comment]
Thanks for the input.
I guess I overlooked that scenario. I'll see if I can fashion an attractive solution without messing around too much with the page height.

**Comment by peterchappell** [comment]
Yeah, it's not a common scenario but it can potentially happen in our app when we show a list of buttons in a dialog. Usually the list has a manageable number of items but it has the potential to be very long.

Thanks for looking into it.

**Comment by tornqvist** [comment]
Let me know if it's not working out for you.

**Comment by peterchappell** [comment]
Yup. That works really well. Thanks very much Carl.

**Comment by peterchappell** [comment]
Just FYI, it doesn't work quite as well when you load content externally (AJAX - using url, rather than content). I guess in this case, the dialog doesn't know how to position itself until the content has loaded...

It's not to bad though - only noticeable for me on large amounts of content in the dialog on a mobile device. And even then if I scroll right to the top of the screen it seems to re-render and sort itself out.

Just thought you might like to know.

Thanks again for your good work.
